# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nice-n-easy}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Landau"]
  s.date = %q{2011-06-06}
  s.description = %q{A set of Sinatra HTML view helpers to make your life nicer and easier. Helpers for forms, links, and assets.}
  s.email = %q{brian.landau@viget.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "deps.rip",
     "lib/sinatra/nice_easy_helpers.rb",
     "nice-n-easy.gemspec",
     "tasks/rdoc.rb",
     "tasks/test.rb",
     "tasks/vendor/sdoc-helpers/markdown.rb",
     "tasks/vendor/sdoc-helpers/pages.rb",
     "test/nice_easy_helpers_test.rb",
     "test/tag_matcher.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/brianjlandau/nice-n-easy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sinatra HTML helpers that are nice-n-easy to use.}
  s.test_files = [
    "test/nice_easy_helpers_test.rb",
     "test/tag_matcher.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
  end
end

